services:
  gs-view-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: gs-view-dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
    restart: unless-stopped